services:
  db:
    image: postgres:16-alpine
    container_name: dailymart-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: tannpdev/7-eleven-round2-be:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dailymart-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ecommerce_db
      DB_USER: postgres
      DB_PASSWORD: Postgres@2026
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_SERVER_URL=http://localhost:8080/api
    container_name: dailymart-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
